### ISSUE TITLE
Weather Effects

### ISSUE THREAD

**Issue by philbgarner** [philbgarner/MudNode#2]
Areas should have weather effects that are more or less globally applied in that area.  Weather should depend on factors such as season and time of day, etc.

**Comment by AdamPawlicki** [comment]
Question to ponder.

Make all weather effects physical objects affecting room.

Example.

10 inch snow layer has following effects.

Weigh kg/m^2

Height 10 inch
Can interact with objects such as vegetation (if plant height is lower than 10inch then removes those plants from scan command (look around: more detailed description of room). Also makes harder to search for plant.
Can also interact with mobiles like animals, humanoids etc based on their height and type of movement.

A light small animal can run on top of it, human will fall in it. Short human or a child will have movement heavily impaired, but tall human will be affected less.

Player would have two options: spend aditional endurance to move at normal pace, or can walk slower at the normal energy expenditure.

A deer will be affected according to his stats too. Things like birds or giants would be unaffected.

Different scenario in falling snow etc.

**Comment by AdamPawlicki** [comment]
Time of the day and year is basicaly sun exposition.

Check breeze.

Next to sea or big bodies of water, you always have a wind blowing from the land into the sea in thr evening and at in the morning direction of wind is reversed.

Relative temperature of water next to the shore is higher than that of land mass after sunset and lower in the morning.

Big mountain ranges 2000m + act as barrier for low clouds so in mountains weather tend to shift more dramatically without notice.

Coastal regions tend to have milder climate.

Big landmasses have harsher climate

**Comment by AdamPawlicki** [comment]
Some more about hydrology.

Densly forested areas have higher water retention levels. Trees and vegetation holds excess water working as a natural buffer or dam.
