### ISSUE TITLE
Dynamic Descriptions System

### ISSUE THREAD

**Issue by philbgarner** [philbgarner/MudNode#8]
Entities should have a Describe() method that takes environmental, seasonal, weather and time of day factors in to how it's described.

For example:
A rabbit might describe itself as having brown and white fur, but in the winter it is white.
In the rain a dusty road becomes a muddy road.
In the spring a field is freshly tilled, in the fall it is full of tall sheaves of wheat.
During the day a market place is a densely packed throng of people, at night it's an eerily quiet and full of threatening shadows.

Not sure how to design this yet.

**Comment by AdamPawlicki** [comment]
Look up object (road) from database each time when description is presented (when you walk into the room).

If you have object such as rainwater in the room, you check different address of how 'path' looks like.

Likewise, if days of the year is 1-70 and 330-365 then rsbbit is rabbit_winter_fur. Instead of rabbit_green_seasons_fur.

Not sure if it helps :)

**Comment by AdamPawlicki** [comment]
Basically whatever is in room (water  snow, rain, wind), those work like debuff or buff spells.

Time of the year is global debuff spell.

**Comment by philbgarner** [comment]
Yeah this is totally doable, I implemented the procedural text generator last night as the grammar module, but right now it's a global dictionary (a list that all other modules would refer to).  After sleeping on it I realize it would be useful to be able to store grammar dictionaries at other levels than just globally, like maybe having a list called "winter_fur" at the global level which can be superseded by a list called "winter_fur" stored at the Entity level.

So if you have an entity that doesn't have a key called "winter_fur" set in its dictionary, when the Entity describes itself it uses the "winter_fur" from the global level (world defaults).  If your custom Entity does have a key set though (like if you made your Rabbit entity) it would use the descriptors you assigned to the "winter_fur" key the Rabbit entity has.

I hope that makes sense.

I want to add some contextual information in the [*key name] syntax in the future so you could do conditional stuff inline, like maybe seasonal changes are specified in your template with notation like `[?season:winter_fur,spring_fur,summer_fur,autumn_fur]` The way the template processes that would be something like this:

```
if season = 0 then use winter_fur
if season = 1 then use spring_fur
if season = 2 then use summer_fur
if season = 3 then use autumn_fur
```
The season number would be a global number value that the calendar module knows and can be exposed to the grammar module for this kind of use.

I'm thinking of making some UIs that make entering/modifying all of this data faster and easier, because it's all done right now through editing JSON files. :P

**Comment by AdamPawlicki** [comment]
I was looking at somethibg like this yesterday. For tree seeds and leaves.

Break down calendar into weeks of the year.

1st - 9th week gives you naked branches, no leaves.
10th week gives you some little buds on twigs.
11-12th week gives you twig sprouts growing
13-14th week gives you greening of the tree etc.

**Comment by philbgarner** [comment]
All of this should be possible now with recent commits, closing ticket.
